name: semantic-version

description: Standard semantic versioning config

inputs:
  debug:
    description: "Enable debug logging"
    required: false
    default: "false"

outputs:
  version:
    value: ${{ steps.version.outputs.version }}

runs:
  using: composite
  steps:
    - id: version
      # Upstream Release forked at v6.0.2
      uses: qcode-software/semantic-version@289d80945967c179308b431dbfff17dd56def0ab
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}"
        bump_each_commit: true
        search_commit_body: true
        debug: ${{ inputs.debug }}

