name: 'Proc Length Check'

on:
  workflow_call:
    inputs:
      files:
        description: 'List of files to check for changes.'
        required: true
        type: string
      max_proc_body_length:
        description: 'The maximum number of lines that a proc body can be.' 
        default: 150
        required: false
        type: number

jobs:
  proc-length-check:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install tclsh tcllib tdom tclcurl libpgtcl

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Qcode CI
        uses: actions/checkout@v3
        with:
          repository: qcode-software/ci-development
          path: qcode-ci

      - name: Get Changed Tcl Script Files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: ${{ inputs.files }}

      - name: Check Proc Lengths
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Checking proc body lengths in files: \
            ${{ steps.changed-files.outputs.all_changed_files }}"
          cd ${{ github.workspace }}/qcode-ci/scripts
          tclsh proc-length-check.tcl \
            ${{ github.workspace }}/qcode-ci/tcl/linter.tcl \
            ${{ inputs.max_proc_body_length }} \
            ${{ github.workspace }} \
            ${{ steps.changed-files.outputs.all_changed_files }}