name: 'Pull Request Linting'

on:
  pull_request:
    paths:
      - '**.tcl'

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/qcode-ci.yml
    with:
      files: |
        scripts/**/*.tcl
      tcl_directory: scripts
      max_line_length: 90
      max_file_length: 500
      check_line_lengths: true
      check_proc_names: true
      check_procs_have_unit_tests: true
      check_file_lengths: true
      check_proc_lengths: true
      check_proc_comments: true
    secrets: inherit