name: 'Pull Request Linting'

on:
  pull_request:
    paths:
      - '**.tcl'

jobs:
  linting:
    name: Linting
    uses: ./.github/workflows/qcode-ci.yml
    with:
      files: |
        scripts/**.tcl
        tcl/**.tcl
      test_directory: tests
      max_line_length: 90
      max_file_length: 500
      max_proc_body_length: 80
      check_line_lengths: true
      check_proc_names: true
      check_procs_have_unit_tests: true
      check_file_lengths: true
      check_proc_lengths: true
    secrets: inherit