name: 'Qcode CI'

on:
  workflow_call:
    inputs:
      max_line_length:
        description: 'The maximum number of characters that a line can be.'
        default: 90
        required: false
        type: number
      max_file_length:
        description: 'The maximum number of lines that a file can be.'
        default: 500
        required: false
        type: number
      check_line_lengths:
        description: 'Flag for checking line lengths.'
        default: true
        required: false
        type: boolean
      check_proc_names:
        description: 'Flag for checking that proc names are prefixed with the file name.'
        default: true
        required: false
        type: boolean
      check_procs_have_unit_tests:
        description: 'Flag for checking that procs have unit tests.'
        default: true
        required: false
        type: boolean
      check_file_lengths:
        description: 'Flag for checking file lengths.'
        default: true
        required: false
        type: boolean
      files:
        description: 'List of files to check for changes.'
        required: true
        type: string
      test_directory:
        description: 'Directory within the repository where test files are located.'
        default: test
        required: false
        type: string

jobs:
  line_length_check:
    name: Check for Lines Exceeding Max Chars
    if: inputs.check_line_lengths
    uses: ./.github/workflows/line-length-check.yml
    with:
      max_line_length: ${{ inputs.max_line_length }}
      files: ${{ inputs.files }}
    secrets: inherit

  proc_name_check:
    name: Check for Proc Names Not Prefixed with File Name
    if: inputs.check_proc_names
    uses: ./.github/workflows/proc-name-check.yml
    with:
      files: ${{ inputs.files }}
    secrets: inherit

  procs_have_unit_tests_check:
    name: Check Procs Have Unit Tests
    if: inputs.check_procs_have_unit_tests
    uses: ./.github/workflows/procs-have-unit-tests-check.yml
    with:
      test_directory: ${{ inputs.test_directory }}
      files: ${{ inputs.files }}
    secrets: inherit

  file_length_check:
    name: Check for Files Exceeding Max Lines
    if: inputs.check_file_lengths
    uses: ./.github/workflows/file-length-check.yml
    with:
      max_file_length: ${{ inputs.max_file_length }}
      files: ${{ inputs.files }}
    secrets: inherit