name: 'Qcode CI'

on:
  workflow_call:
    inputs:
      max_line_length:
        description: 'The maximum number of characters that a line can be.'
        default: 90
        required: false
        type: number
      max_file_length:
        description: 'The maximum number of lines that a file can be.'
        default: 500
        required: false
        type: number
      max_proc_body_length:
        description: 'The maximum number of lines that a proc body can be.' 
        default: 80
        required: false
        type: number
      check_line_lengths:
        description: 'Flag for checking line lengths.'
        default: true
        required: false
        type: boolean
      check_proc_names:
        description: 'Flag for checking that proc names are prefixed with the file name.'
        default: true
        required: false
        type: boolean
      check_procs_have_unit_tests:
        description: 'Flag for checking that procs have unit tests.'
        default: true
        required: false
        type: boolean
      check_file_lengths:
        description: 'Flag for checking file lengths.'
        default: true
        required: false
        type: boolean
      check_proc_lengths:
        description: 'Flag for checking proc body lengths.'
        default: true
        required: false
        type: boolean
      files:
        description: 'List of files to check for changes.'
        required: true
        type: string
      test_directory:
        description: 'Directory within the repository where test files are located.'
        default: test
        required: false
        type: string

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install tclsh tcllib tdom tclcurl libpgtcl

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout Qcode CI
        uses: actions/checkout@v3
        with:
          repository: qcode-software/ci-development
          path: qcode-ci

      - name: Get Changed Tcl Script Files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: ${{ inputs.files }}

      - name: Check for Lines Exceeding Max Chars
        id: check-line-length
        if: >
          always()
          && steps.changed-files.outcome == 'success'
          && inputs.check_line_lengths
          && steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd ${{ github.workspace }}/qcode-ci/scripts
          tclsh line-length-check.tcl \
            ${{ github.workspace }}/qcode-ci/tcl/linter.tcl \
            ${{ inputs.max_line_length }} \
            ${{ github.workspace }} \
            ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Check for Proc Names Not Prefixed with File Name
        if: >
          always()
          && steps.changed-files.outcome == 'success'
          && inputs.check_proc_names
          && steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd ${{ github.workspace }}/qcode-ci/scripts
          tclsh proc-name-check.tcl \
            ${{ github.workspace }}/qcode-ci/tcl/linter.tcl \
            ${{ github.workspace }} \
            ${{ steps.changed-files.outputs.all_changed_files }}


      - name: Check for Proc Bodies Exceeding Max Lines
        if: >
          always()
          && steps.changed-files.outcome == 'success'
          && inputs.check_proc_lengths
          && steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd ${{ github.workspace }}/qcode-ci/scripts
          tclsh proc-length-check.tcl \
            ${{ github.workspace }}/qcode-ci/tcl/linter.tcl \
            ${{ inputs.max_proc_body_length }} \
            ${{ github.workspace }} \
            ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Check Procs Have Unit Tests
        if: >
          always()
          && steps.changed-files.outcome == 'success'
          && inputs.check_procs_have_unit_tests
          && steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd ${{ github.workspace }}/qcode-ci/scripts
          tclsh procs-have-unit-tests-check.tcl \
            ${{ github.workspace }}/qcode-ci/tcl/test_coverage.tcl \
            ${{ github.workspace }} \
            ${{ inputs.test_directory }} \
            ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Check for Files Exceeding Max Lines
        if: >
          always()
          && steps.changed-files.outcome == 'success'
          && inputs.check_file_lengths
          && steps.changed-files.outputs.any_changed == 'true'
        run: |
          cd ${{ github.workspace }}/qcode-ci/scripts
          tclsh file-length-check.tcl \
            ${{ github.workspace }}/qcode-ci/tcl/linter.tcl \
            ${{ inputs.max_file_length }} \
            ${{ github.workspace }} \
            ${{ steps.changed-files.outputs.all_changed_files }}